version: '3'

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list

  tools:
    desc: Install code generation tools
    cmds:
      - go install github.com/tinylib/msgp@latest

  generate:
    desc: Generate all code (protocol and preflop tables)
    deps:
      - generate:protocol
      - generate:preflop

  generate:protocol:
    desc: Generate msgpack protocol code
    cmds:
      - go generate ./protocol
    sources:
      - protocol/messages.go
    generates:
      - protocol/messages_gen.go

  generate:preflop:
    desc: Generate preflop equity tables
    cmds:
      - go generate ./sdk/analysis
      - gofmt -w sdk/analysis/preflop_gen.go
    sources:
      - sdk/analysis/preflop.go
      - cmd/gen-preflop/main.go
    generates:
      - sdk/analysis/preflop_gen.go

  build:
    desc: Build all binaries
    deps:
      - generate
    cmds:
      - mkdir -p dist
      - go build -o dist/pokerforbots ./cmd/pokerforbots
      - go build -o dist/gen-preflop ./cmd/gen-preflop
    sources:
      - '**/*.go'
    generates:
      - dist/pokerforbots
      - dist/gen-preflop

  build:release:
    desc: Build release binaries for distribution
    deps:
      - generate
    cmds:
      - |
        if [ -z "{{.VERSION}}" ]; then
          echo "VERSION is required (e.g. v1.2.3)" >&2
          exit 1
        fi
      - mkdir -p dist
      - rm -f dist/pokerforbots-linux-amd64 dist/pokerforbots-linux-arm64 dist/pokerforbots-darwin-amd64 dist/pokerforbots-darwin-arm64 dist/checksums.txt
      - GOOS=linux GOARCH=amd64 go build -ldflags "-X main.version={{.VERSION}}" -o dist/pokerforbots-linux-amd64 ./cmd/pokerforbots
      - GOOS=linux GOARCH=arm64 go build -ldflags "-X main.version={{.VERSION}}" -o dist/pokerforbots-linux-arm64 ./cmd/pokerforbots
      - GOOS=darwin GOARCH=amd64 go build -ldflags "-X main.version={{.VERSION}}" -o dist/pokerforbots-darwin-amd64 ./cmd/pokerforbots
      - GOOS=darwin GOARCH=arm64 go build -ldflags "-X main.version={{.VERSION}}" -o dist/pokerforbots-darwin-arm64 ./cmd/pokerforbots
      - shasum -a 256 dist/pokerforbots-* > dist/checksums.txt

  install:
    desc: Install pokerforbots to ~/bin
    cmds:
      - mkdir -p ~/bin
      - go build -o ~/bin/pokerforbots ./cmd/pokerforbots
      - echo "Installed to ~/bin/pokerforbots"


  server:
    desc: Run the poker server
    cmds:
      - go run ./cmd/pokerforbots server {{.CLI_ARGS}}

  client:
    desc: Run the poker client
    cmds:
      - go run ./cmd/pokerforbots client {{.CLI_ARGS}}

  spawn:
    desc: Spawn server with bots
    cmds:
      - go run ./cmd/pokerforbots spawn {{.CLI_ARGS}}

  regression:
    desc: Run regression tests
    cmds:
      - go run ./cmd/pokerforbots regression {{.CLI_ARGS}}

  test:
    desc: Run all tests with race detector
    cmds:
      - bin/gotestsum -f pkgname-and-test-fails --format-icons hivis -- -race -parallel 12 ./...

  test:uncached:
    desc: Run all tests without caching
    cmds:
      - bin/gotestsum -f pkgname-and-test-fails --format-icons hivis -- -count=1 -race -parallel 12 ./...

  test:slowest:
    desc: Report slowest tests
    cmds:
      - go test -count=1 -json ./... | gotestsum tool slowest

  lint:
    desc: Run golangci-lint
    cmds:
      - bin/golangci-lint run ./...

  format:
    desc: Format code
    cmds:
      - bin/golangci-lint fmt ./...

  lint:fix:
    desc: Run linters with fix
    cmds:
      - bin/golangci-lint run --fix ./...

  bench:
    desc: Run performance benchmark using spawner
    cmds:
      - go run ./cmd/pokerforbots spawn --spec="calling-station:6" --hand-limit=1000 {{.CLI_ARGS}}
    silent: false

  bench:go:
    desc: Run Go test benchmarks
    cmds:
      - go test -bench=. -benchmem {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}-benchtime=100ms{{end}} ./...

  # Removing duplicate regression task (already defined above)

  regression:heads-up:
    desc: Run heads-up regression test
    cmds:
      - |
        go run ./cmd/pokerforbots regression --mode heads-up \
          --challenger "{{.CHALLENGER | default "./snapshots/complex-latest"}}" \
          --baseline "{{.BASELINE | default "go run ./sdk/examples/complex"}}" \
          --hands {{.HANDS | default "50000"}} \
          --output {{.OUTPUT | default "summary"}} \
          {{if ne .VERBOSE "true"}}--quiet{{end}}

  regression:population:
    desc: Run population regression test
    cmds:
      - |
        go run ./cmd/pokerforbots regression --mode population \
          --challenger "{{.CHALLENGER | default "./snapshots/complex-latest"}}" \
          --baseline "{{.BASELINE | default "go run ./sdk/examples/complex"}}" \
          --hands {{.HANDS | default "50000"}} \
          --output {{.OUTPUT | default "summary"}} \
          {{if ne .VERBOSE "true"}}--quiet{{end}}

  regression:npc:
    desc: Run NPC benchmark regression test
    cmds:
      - |
        go run ./cmd/pokerforbots regression --mode npc-benchmark \
          --challenger "{{.CHALLENGER | default "./snapshots/complex-latest"}}" \
          --baseline "{{.BASELINE | default "go run ./sdk/examples/complex"}}" \
          --hands {{.HANDS | default "50000"}} \
          --output {{.OUTPUT | default "summary"}} \
          {{if ne .VERBOSE "true"}}--quiet{{end}}

  regression:self-play:
    desc: Run self-play regression test
    cmds:
      - |
        go run ./cmd/pokerforbots regression --mode self-play \
          --challenger "{{.CHALLENGER | default "./snapshots/complex-latest"}}" \
          --baseline "{{.BASELINE | default "go run ./sdk/examples/complex"}}" \
          --hands {{.HANDS | default "50000"}} \
          --output {{.OUTPUT | default "summary"}} \
          {{if ne .VERBOSE "true"}}--quiet{{end}}

  regression:all:
    desc: Run all regression test modes sequentially
    cmds:
      - task: regression:heads-up
        vars:
          CHALLENGER: "{{.CHALLENGER}}"
          BASELINE: "{{.BASELINE}}"
          HANDS: "{{.HANDS}}"
          OUTPUT: "{{.OUTPUT}}"
      - task: regression:population
        vars:
          CHALLENGER: "{{.CHALLENGER}}"
          BASELINE: "{{.BASELINE}}"
          HANDS: "{{.HANDS}}"
          OUTPUT: "{{.OUTPUT}}"
      - task: regression:npc
        vars:
          CHALLENGER: "{{.CHALLENGER}}"
          BASELINE: "{{.BASELINE}}"
          HANDS: "{{.HANDS}}"
          OUTPUT: "{{.OUTPUT}}"
      - task: regression:self-play
        vars:
          CHALLENGER: "{{.CHALLENGER}}"
          BASELINE: "{{.BASELINE}}"
          HANDS: "{{.HANDS}}"
          OUTPUT: "{{.OUTPUT}}"

  bench:evaluator:
    desc: Run evaluator large-sample benchmarks (sequential and parallel)
    cmds:
      - go test -run ^$ -bench BenchmarkEvaluate7Cards_LargeSample$ -benchmem ./poker {{.CLI_ARGS}}
      - go test -run ^$ -bench BenchmarkEvaluate7Cards_LargeSample_Parallel$ -benchmem ./poker {{.CLI_ARGS}}

  profile:evaluator:top:
    desc: Quick top-10 CPU for non-parallel evaluator benchmark (pprof)
    cmds:
      - mkdir -p dist
      - go test -c -o dist/evaluator.test ./poker
      - ./dist/evaluator.test -test.run=^$ -test.bench=^BenchmarkEvaluate7Cards_LargeSample$ -test.count=1 -test.benchtime=10s -test.cpuprofile=dist/eval-seq.pprof {{.CLI_ARGS}}
      - go tool pprof -top -nodecount=10 ./dist/evaluator.test dist/eval-seq.pprof

  profile:handrunner:top:
    desc: CPU profile of hand runner benchmark (top 10)
    cmds:
      - mkdir -p dist
      - go test -c -o dist/internal_server.test ./internal/server
      - ./dist/internal_server.test -test.run=^$ -test.bench=^BenchmarkHandRunnerHeadsUpFold$ -test.count=1 -test.benchtime=10s -test.cpuprofile=dist/handrunner.pprof {{.CLI_ARGS}}
      - go tool pprof -top -nodecount=10 ./dist/internal_server.test dist/handrunner.pprof

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf dist/
      - rm -f protocol/*_gen.go
      - rm -f protocol/*_gen_test.go
