version: '3'

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list

  generate:
    desc: Generate msgpack code
    cmds:
      - go generate ./...
    sources:
      - internal/protocol/messages.go
    generates:
      - internal/protocol/messages_gen.go

  build:
    desc: Build all binaries
    cmds:
      - mkdir -p dist
      - go build -o dist/server cmd/server/main.go
      - go build -o dist/testbot cmd/testbot/main.go
      - go build -o dist/simulate cmd/simulate/main.go
      - go build -o dist/spawn-bots cmd/spawn-bots/main.go
    sources:
      - '**/*.go'
    generates:
      - dist/server
      - dist/testbot
      - dist/simulate
      - dist/spawn-bots

  server:
    desc: Run the poker server
    deps: [build]
    cmds:
      - ./dist/server

  simulate:
    desc: Run single hand simulation (no networking)
    deps: [build]
    cmds:
      - ./dist/simulate {{.CLI_ARGS}}

  spawn-bots:
    desc: Spawn bots to connect to server (or spawn server)
    deps: [build]
    cmds:
      - ./dist/spawn-bots {{.CLI_ARGS}}

  test:
    desc: Run all tests with race detector
    cmds:
      - bin/gotestsum -f pkgname-and-test-fails --format-icons hivis -- -race ./...

  lint:
    desc: Run linters
    cmds:
      - bin/golangci-lint run ./...

  format:
    desc: Format code
    cmds:
      - bin/golangci-lint fmt ./...

  bench:
    desc: Run benchmarks
    cmds:
      - go test -bench=. -benchmem ./...

  demo:
    desc: Run interactive demo with 6 bots for 50 hands
    deps: [build]
    cmds:
      - ./dist/spawn-bots --spawn-server --bots 6 --hands 50

  test-1000:
    desc: Test 1000 hands completion
    deps: [build]
    cmds:
      - ./dist/spawn-bots --spawn-server --bots 6 --hands 1000 --quiet

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf dist/
      - rm -f internal/protocol/*_gen.go
      - rm -f internal/protocol/*_gen_test.go

  install-deps:
    desc: Install project dependencies
    cmds:
      - go get github.com/gorilla/websocket
      - go get github.com/tinylib/msgp
      - go install github.com/tinylib/msgp@latest
