version: '3'

vars:
  DIST_DIR: dist
  BINARY_NAME: holdem
  GO_MODULE: github.com/lox/pokerforbots

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  test:
    desc: Run all tests
    cmds:
      - bin/gotestsum --format testname -- ./...

  test-verbose:
    desc: Run tests with verbose output
    cmds:
      - bin/gotestsum --format testname -- -v ./...

  lint:
    desc: Run linter (golangci-lint)
    cmds:
      - bin/golangci-lint run

  fmt:
    desc: Format Go code
    cmds:
      - go fmt ./...
      - goimports -w .

  build:
    desc: Build the application
    deps: [clean]
    cmds:
      - mkdir -p {{.DIST_DIR}}
      - go build -o {{.DIST_DIR}}/holdem-server ./cmd/holdem-server
      - go build -o {{.DIST_DIR}}/holdem-client ./cmd/holdem-client
      - go build -o {{.DIST_DIR}}/poker-odds ./cmd/poker-odds

  build-all:
    desc: Build for multiple platforms
    deps: [clean]
    cmds:
      - mkdir -p {{.DIST_DIR}}
      - GOOS=linux GOARCH=amd64 go build -o {{.DIST_DIR}}/holdem-server-linux-amd64 ./cmd/holdem-server
      - GOOS=darwin GOARCH=amd64 go build -o {{.DIST_DIR}}/holdem-server-darwin-amd64 ./cmd/holdem-server
      - GOOS=darwin GOARCH=arm64 go build -o {{.DIST_DIR}}/holdem-server-darwin-arm64 ./cmd/holdem-server
      - GOOS=windows GOARCH=amd64 go build -o {{.DIST_DIR}}/holdem-server-windows-amd64.exe ./cmd/holdem-server
      - GOOS=linux GOARCH=amd64 go build -o {{.DIST_DIR}}/holdem-client-linux-amd64 ./cmd/holdem-client
      - GOOS=darwin GOARCH=amd64 go build -o {{.DIST_DIR}}/holdem-client-darwin-amd64 ./cmd/holdem-client
      - GOOS=darwin GOARCH=arm64 go build -o {{.DIST_DIR}}/holdem-client-darwin-arm64 ./cmd/holdem-client
      - GOOS=windows GOARCH=amd64 go build -o {{.DIST_DIR}}/holdem-client-windows-amd64.exe ./cmd/holdem-client
      - GOOS=linux GOARCH=amd64 go build -o {{.DIST_DIR}}/poker-odds-linux-amd64 ./cmd/poker-odds
      - GOOS=darwin GOARCH=amd64 go build -o {{.DIST_DIR}}/poker-odds-darwin-amd64 ./cmd/poker-odds
      - GOOS=darwin GOARCH=arm64 go build -o {{.DIST_DIR}}/poker-odds-darwin-arm64 ./cmd/poker-odds
      - GOOS=windows GOARCH=amd64 go build -o {{.DIST_DIR}}/poker-odds-windows-amd64.exe ./cmd/poker-odds

  run:
    desc: Run the server application
    cmds:
      - go run ./cmd/holdem-server

  run-client:
    desc: Run the client application
    cmds:
      - go run ./cmd/holdem-client

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.DIST_DIR}}
      - rm -f coverage.out coverage.html

  deps:
    desc: Download dependencies
    cmds:
      - go mod download
      - go mod tidy

  check:
    desc: Run all checks (test, lint, build)
    deps: [test, lint, build]

  dev:
    desc: Development setup - format, test, lint
    deps: [fmt, test, lint]
