version: '3'

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list

  generate:
    desc: Generate msgpack code
    cmds:
      - go generate ./...
    sources:
      - internal/protocol/messages.go
    generates:
      - internal/protocol/messages_gen.go

  build:
    desc: Build the server
    cmds:
      - mkdir -p dist
      - go build -o dist/server cmd/server/main.go
      - go build -o dist/testbot cmd/testbot/main.go
    sources:
      - '**/*.go'
    generates:
      - dist/server
      - dist/testbot

  run:
    desc: Run the server
    deps: [build]
    cmds:
      - ./dist/server

  test:
    desc: Run all tests
    cmds:
      - bin/gotestsum -f pkgname-and-test-fails --format-icons hivis ./...

  lint:
    desc: Run linters
    cmds:
      - bin/golangci-lint run ./...

  format:
    desc: Format code
    cmds:
      - bin/golangci-lint fmt ./...

  bench:
    desc: Run benchmarks
    cmds:
      - go test -bench=. -benchmem ./...

  demo:
    desc: Run demo with test bots
    deps: [build]
    cmds:
      - ./demo.sh

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf dist/
      - rm -f internal/protocol/*_gen.go
      - rm -f internal/protocol/*_gen_test.go

  install-deps:
    desc: Install project dependencies
    cmds:
      - go get github.com/gorilla/websocket
      - go get github.com/tinylib/msgp
      - go install github.com/tinylib/msgp@latest
