version: '3'

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list

  generate:
    desc: Generate msgpack code
    cmds:
      - go generate ./...
    sources:
      - internal/protocol/messages.go
    generates:
      - internal/protocol/messages_gen.go

  build:
    desc: Build all binaries
    cmds:
      - mkdir -p dist
      - go build -o dist/server cmd/server/main.go
      - go build -o dist/client cmd/client/main.go
      - go build -o dist/benchmark cmd/benchmark/main.go
    sources:
      - '**/*.go'
    generates:
      - dist/server
      - dist/client
      - dist/benchmark

  server:
    desc: Run the poker server
    cmds:
      - go run ./cmd/server {{.CLI_ARGS}}

  client:
    desc: Run the poker client
    cmds:
      - go run ./cmd/client {{.CLI_ARGS}}

  simulate:
    desc: Run single hand simulation (no networking)
    cmds:
      - go run ./cmd/simulate {{.CLI_ARGS}}

  test:
    desc: Run all tests with race detector
    cmds:
      - bin/gotestsum -f pkgname-and-test-fails --format-icons hivis -- -race -parallel 12 ./...

  test:slowest:
    desc: Report slowest tests (short mode)
    cmds:
      - go test -json -short ./... | gotestsum tool slowest

  lint:
    desc: Run linters
    cmds:
      - bin/golangci-lint run ./...

  format:
    desc: Format code
    cmds:
      - bin/golangci-lint fmt ./...

  bench:
    desc: Run WebSocket performance benchmark
    cmds:
      - go run ./cmd/benchmark {{.CLI_ARGS}}
    silent: false

  bench:go:
    desc: Run Go test benchmarks
    cmds:
      - go test -bench=. -benchmem ./...

  bench:evaluator:
    desc: Run evaluator large-sample benchmarks (sequential and parallel)
    cmds:
      - go test -run ^$ -bench BenchmarkEvaluate7Cards_LargeSample$ -benchmem ./internal/game {{.CLI_ARGS}}
      - go test -run ^$ -bench BenchmarkEvaluate7Cards_LargeSample_Parallel$ -benchmem ./internal/game {{.CLI_ARGS}}

  profile:evaluator:top:
    desc: Quick top-10 CPU for non-parallel evaluator benchmark (pprof)
    cmds:
      - mkdir -p dist
      - go test -c -o dist/evaluator.test ./internal/game
      - ./dist/evaluator.test -test.run=^$ -test.bench=BenchmarkEvaluate7Cards_LargeSample -test.count=1 -test.benchtime=10s -test.cpuprofile=dist/eval-seq.pprof {{.CLI_ARGS}}
      - go tool pprof -top -nodecount=10 ./dist/evaluator.test dist/eval-seq.pprof

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf dist/
      - rm -f internal/protocol/*_gen.go
      - rm -f internal/protocol/*_gen_test.go
