//go:build ignore
// +build ignore

// Command gen_perfect_hash builds the perfect hash lookup tables for 7-card
// evaluation and writes them to ph_tables.go.  It is invoked via:
//
//	go generate
//
// Expect the process to take a couple of minutes and consume a few GB of RAM.
//
// The algorithm mirrors the classic C "7-card evaluator" generator: iterate over
// every 7-card combination, compute its HandRank via the legacy evaluator, then
// fill the suited/unsuited tables keyed by rank-bitmap or prime product.
//
// Because the resulting tables are large we marshal them as Go literal maps.  A
// future optimisation would compress them into slices with a two-stage perfect
// hash, but this simple approach is quite fast on contemporary machines.
package main

import (
	"bufio"
	"fmt"
	"log"
	"os"
	"sort"

	"github.com/lox/pokerforbots/internal/deck"
	"github.com/lox/pokerforbots/internal/evaluator"
)

var primeRank = [...]int{
	0, 0, // 0,1 unused
	2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41,
}

func main() {
	// Build full 52-card deck
	var deck52 [52]deck.Card
	idx := 0
	for s := 0; s < 4; s++ {
		for r := 2; r <= 14; r++ {
			deck52[idx] = deck.NewCard(s, r)
			idx++
		}
	}

	flushTable := make(map[int]evaluator.HandRank, 1000000)
	unsuitedTable := make(map[int]evaluator.HandRank, 5000000)

	var cards [7]deck.Card
	var comb func(int, int, int)
	comb = func(start, depth, k int) {
		if depth == k {
			rank := evaluator.Evaluate7Legacy(cards[:])

			// Accumulate suit counts and rank bitmap/product
			var suitCounts [4]int
			rb := 0
			prod := 1
			for _, c := range cards {
				suitCounts[c.Suit]++
				rb |= 1 << (c.Rank - 2)
				prod *= primeRank[c.Rank]
			}

			// detect flush
			flush := -1
			for s, cnt := range suitCounts {
				if cnt >= 5 {
					flush = s
					break
				}
			}
			if flush != -1 {
				// rebuild bitmap for flush suit
				frb := 0
				for _, c := range cards {
					if c.Suit == flush {
						frb |= 1 << (c.Rank - 2)
					}
				}
				flushTable[frb] = rank
			} else {
				unsuitedTable[prod] = rank
			}
			return
		}
		for i := start; i <= 52-(k-depth); i++ {
			cards[depth] = deck52[i]
			comb(i+1, depth+1, k)
		}
	}

	log.Println("Enumerating 7-card combinations (this will take a while)…")
	comb(0, 0, 7)

	// Serialise to Go code
	// Write tables beside the generator inside the evaluator package so that
	// they compile into the same Go package regardless of where `go generate`
	// was invoked from.
	f, err := os.Create("ph_tables.go")
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()
	w := bufio.NewWriter(f)
	fmt.Fprintln(w, "// Code generated by gen_perfect_hash.go; DO NOT EDIT.")
	fmt.Fprintln(w, "package evaluator\n")

	// Emit flushTable as a dense slice keyed by rank bitmap (max key fits in
	// 13 bits => 8192). We create a fixed-length literal so look-ups are O(1)
	// array indexing at runtime.

	// Find maximum flush key to size slice
	maxFlushKey := 0
	for k := range flushTable {
		if k > maxFlushKey {
			maxFlushKey = k
		}
	}

	fmt.Fprintln(w, "func init() {")
	fmt.Fprintf(w, "    flushTable = []HandRank{\n")
	for i := 0; i <= maxFlushKey; i++ {
		if v, ok := flushTable[i]; ok {
			fmt.Fprintf(w, "        %d, // %d\n", v, i)
		} else {
			fmt.Fprintln(w, "        0,")
		}
	}
	fmt.Fprintln(w, "    }\n")

	// Now emit unsuitedTable as a map (sparse key space)
	//
	// OPTIMIZATION NOTE: We use Go's built-in map rather than custom data structures
	// because benchmarks showed maps outperform manual optimizations:
	// - Map lookup: ~35ns (current implementation)
	// - Bucketed linear scan: ~58ns (stashed in git)
	// - Binary search: ~105ns (cache misses)
	// Go's map implementation benefits from hardware acceleration and years of optimization.

	// Emit unsuitedTable as a map
	unsKeys := make([]int, 0, len(unsuitedTable))
	for k := range unsuitedTable {
		unsKeys = append(unsKeys, k)
	}
	sort.Ints(unsKeys)

	fmt.Fprintf(w, "    unsuitedTable = map[int]HandRank{\n")
	for _, k := range unsKeys {
		fmt.Fprintf(w, "        %d: %d,\n", k, unsuitedTable[k])
	}
	fmt.Fprintln(w, "    }\n")

	fmt.Fprintln(w, "    perfectHashReady = true\n}")

	if err := w.Flush(); err != nil {
		log.Fatal(err)
	}

	log.Println("Generated ph_tables.go with", len(flushTable), "flush entries and", len(unsuitedTable), "unsuited entries.")
}
